import { useState } from "react";

const VALID_CATEGORIES = new Set(["Strength", "Running", "Ball Sports"]);

function aiWorkoutToCustom(w) {
  const category = VALID_CATEGORIES.has(w.category) ? w.category : "Strength";
  const cleanPhase = (arr, isMain) =>
    Array.isArray(arr)
      ? arr
          .filter((it) => it && it.name)
          .map((it) =>
            isMain
              ? {
                  exerciseId: null,
                  name: String(it.name),
                  sets: parseInt(it.sets) || 3,
                  reps: String(it.reps ?? it.duration ?? "10"),
                }
              : { exerciseId: null, name: String(it.name), duration: String(it.duration || "30 sec") }
          )
      : [];

  return {
    id: `custom_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
    title: w.title || "AI Workout",
    category,
    subcategory: null,
    difficulty: "Custom",
    duration: parseInt(w.duration) || 30,
    equipment: [],
    description: w.reason || "Generated by AI Coach",
    isCustom: true,
    warmup:   cleanPhase(w.warmup, false),
    main:     cleanPhase(w.main, true),
    cooldown: cleanPhase(w.cooldown, false),
  };
}

function WorkoutPreview({ workout, onSave }) {
  const [saved, setSaved] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const handleSave = () => {
    onSave(aiWorkoutToCustom(workout));
    setSaved(true);
  };

  return (
    <div className="bg-neutral-950 border border-neutral-800 pixel-card p-3">
      <div className="flex items-start justify-between gap-2 mb-1">
        <p className="text-white text-sm font-medium flex-1">{workout.title}</p>
        <span className="font-display text-neutral-600 flex-shrink-0" style={{ fontSize: "6px", letterSpacing: "0.1em" }}>
          {workout.duration}M
        </span>
      </div>
      <p className="text-neutral-600 text-xs mb-2">{workout.category} · {workout.main?.length || 0} exercises</p>
      {workout.reason && <p className="text-neutral-500 text-xs italic mb-2">{workout.reason}</p>}

      <button
        onClick={() => setExpanded((v) => !v)}
        className="font-display text-neutral-600 hover:text-neutral-400 transition-colors mb-2"
        style={{ fontSize: "6px", letterSpacing: "0.12em" }}
      >
        {expanded ? "▾ HIDE" : "▸ SHOW EXERCISES"}
      </button>

      {expanded && (
        <div className="mb-3 text-xs space-y-2">
          {workout.warmup?.length > 0 && (
            <div>
              <p className="font-display" style={{ fontSize: "6px", letterSpacing: "0.12em", color: "#fb923c" }}>WARM-UP</p>
              {workout.warmup.map((it, i) => (
                <p key={i} className="text-neutral-400">· {it.name} <span className="text-neutral-600">— {it.duration}</span></p>
              ))}
            </div>
          )}
          {workout.main?.length > 0 && (
            <div>
              <p className="font-display" style={{ fontSize: "6px", letterSpacing: "0.12em", color: "var(--accent)" }}>MAIN</p>
              {workout.main.map((it, i) => (
                <p key={i} className="text-neutral-400">· {it.name} <span className="text-neutral-600">— {it.sets || 3} × {it.reps || it.duration || "10"}</span></p>
              ))}
            </div>
          )}
          {workout.cooldown?.length > 0 && (
            <div>
              <p className="font-display" style={{ fontSize: "6px", letterSpacing: "0.12em", color: "#38bdf8" }}>COOL-DOWN</p>
              {workout.cooldown.map((it, i) => (
                <p key={i} className="text-neutral-400">· {it.name} <span className="text-neutral-600">— {it.duration}</span></p>
              ))}
            </div>
          )}
        </div>
      )}

      <button
        onClick={handleSave}
        disabled={saved}
        className="w-full py-2 font-display text-neutral-950 pixel-btn disabled:opacity-40 transition-opacity"
        style={{ background: saved ? "#6ea825" : "var(--accent)", fontSize: "7px", letterSpacing: "0.12em" }}
      >
        {saved ? "✓ SAVED TO MY WORKOUTS" : "+ SAVE AS WORKOUT"}
      </button>
    </div>
  );
}

export default function AICoach({ profile, history = [], onSaveWorkout }) {
  const [loading, setLoading]   = useState(false);
  const [analysis, setAnalysis] = useState("");
  const [workouts, setWorkouts] = useState([]);
  const [error, setError]       = useState(null);

  const ask = async () => {
    setLoading(true);
    setError(null);
    setAnalysis("");
    setWorkouts([]);
    try {
      const response = await fetch("/api/recommend", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          profile: {
            name:      profile?.name,
            level:     profile?.level,
            equipment: profile?.equipment,
          },
          history: history.slice(0, 30).map((h) => ({
            date:       h.date,
            title:      h.title,
            duration:   h.duration,
            stars:      h.stars,
            categories: h.categories,
          })),
        }),
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Request failed");
      setAnalysis(data.analysis || "");
      setWorkouts(data.workouts || []);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const hasResult = analysis || workouts.length > 0;

  return (
    <div className="mb-8">
      <h2 className="font-display text-white mb-3" style={{ fontSize: "9px", letterSpacing: "0.12em" }}>
        AI COACH ✨
      </h2>
      <div className="bg-neutral-900 pixel-card p-4">
        {!hasResult && !loading && !error && (
          <>
            <p className="text-neutral-500 text-sm mb-3">
              Get an AI analysis of your recent workouts and personalized recommendations you can save.
            </p>
            <button
              onClick={ask}
              disabled={history.length === 0}
              className="w-full py-2.5 font-display text-neutral-950 pixel-btn disabled:opacity-40"
              style={{ background: "var(--accent)", fontSize: "8px", letterSpacing: "0.12em" }}
            >
              {history.length === 0 ? "LOG A WORKOUT FIRST" : "✨ ANALYZE MY WORKOUTS"}
            </button>
          </>
        )}

        {loading && (
          <p className="text-neutral-500 py-3 text-center font-display" style={{ fontSize: "8px", letterSpacing: "0.15em" }}>
            THINKING...
          </p>
        )}

        {error && (
          <>
            <p className="text-red-400 text-xs mb-3">{error}</p>
            <button
              onClick={ask}
              className="w-full py-2 font-display text-neutral-400 border border-neutral-700 hover:border-neutral-500 hover:text-neutral-200 transition-colors"
              style={{ fontSize: "7px", letterSpacing: "0.12em" }}
            >
              TRY AGAIN
            </button>
          </>
        )}

        {hasResult && (
          <>
            {analysis && (
              <p className="text-neutral-300 text-sm leading-relaxed mb-4">{analysis}</p>
            )}
            {workouts.length > 0 && (
              <div className="flex flex-col gap-2 mb-3">
                {workouts.map((w, i) => (
                  <WorkoutPreview key={i} workout={w} onSave={onSaveWorkout} />
                ))}
              </div>
            )}
            <button
              onClick={ask}
              className="w-full py-2 font-display text-neutral-500 border border-neutral-700 hover:border-neutral-500 hover:text-neutral-300 transition-colors"
              style={{ fontSize: "7px", letterSpacing: "0.12em" }}
            >
              ↻ REGENERATE
            </button>
          </>
        )}
      </div>
    </div>
  );
}
